[package]
name = "memfs"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
env_logger = "0.11.8"
lazy_static = "1.5.0"
tokio = { version = "1.44.2", features = ["full"] }
tokio-test = "0.4.4"

